### ISSUE TITLE
`Please update hashcat to v6.2.6`

### ISSUE THREAD

**Issue by OmiChrome** [bannsec/hashcat#2]
The pip package is soo usefull
it makes installtion easy .
and also let bypass sudo / root powers 
which is must .
so please update hashcat-pip. 
its soo usefull

**Comment by bannsec** [comment]
Yeah super helpful for me too. problem has been that pypi put in a file size limit for packages and hashcat basically bloated up. I've got a request in with pypi to allow a higher limit for this repo, so fingers crossed.

**Comment by bannsec** [comment]
Got approval from pypi to push larger images. Autorun build is up and working again and new version 6.2.6 was pushed. Cron deploys are running again. Looks like life is good.
